//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: mimc.proto
namespace mimc
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FilterRequest")]
  public partial class FilterRequest : global::ProtoBuf.IExtensible
  {
    public FilterRequest() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private mimc.MIMCPacket _packet;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"packet", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public mimc.MIMCPacket packet
    {
      get { return _packet; }
      set { _packet = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FilterResponse")]
  public partial class FilterResponse : global::ProtoBuf.IExtensible
  {
    public FilterResponse() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }

    private mimc.MIMC_MSG_TYPE _type = mimc.MIMC_MSG_TYPE.P2P_MESSAGE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(mimc.MIMC_MSG_TYPE.P2P_MESSAGE)]
    public mimc.MIMC_MSG_TYPE type
    {
      get { return _type; }
      set { _type = value; }
    }

    private mimc.ErrorCode _errorCode = mimc.ErrorCode.OK;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(mimc.ErrorCode.OK)]
    public mimc.ErrorCode errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }

    private bool _isFilter = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isFilter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isFilter
    {
      get { return _isFilter; }
      set { _isFilter = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PullMessageRequest")]
  public partial class PullMessageRequest : global::ProtoBuf.IExtensible
  {
    public PullMessageRequest() {}
    
    private ulong _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private string _resource;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string resource
    {
      get { return _resource; }
      set { _resource = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TopicMessage")]
  public partial class TopicMessage : global::ProtoBuf.IExtensible
  {
    public TopicMessage() {}
    
    private ulong _topicId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"topicId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong topicId
    {
      get { return _topicId; }
      set { _topicId = value; }
    }
    private mimc.MIMCPacket _packet;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"packet", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public mimc.MIMCPacket packet
    {
      get { return _packet; }
      set { _packet = value; }
    }

    private long _uuid = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }

    private string _resource = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resource
    {
      get { return _resource; }
      set { _resource = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QueryAppinfoRequest")]
  public partial class QueryAppinfoRequest : global::ProtoBuf.IExtensible
  {
    public QueryAppinfoRequest() {}
    
    private ulong _appId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"appId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong appId
    {
      get { return _appId; }
      set { _appId = value; }
    }

    private string _context = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"context", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string context
    {
      get { return _context; }
      set { _context = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Appinfo")]
  public partial class Appinfo : global::ProtoBuf.IExtensible
  {
    public Appinfo() {}
    
    private ulong _appId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"appId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong appId
    {
      get { return _appId; }
      set { _appId = value; }
    }

    private string _msgCallbackUrl = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"msgCallbackUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string msgCallbackUrl
    {
      get { return _msgCallbackUrl; }
      set { _msgCallbackUrl = value; }
    }

    private string _offlineMsgCallbackUrl = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"offlineMsgCallbackUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string offlineMsgCallbackUrl
    {
      get { return _offlineMsgCallbackUrl; }
      set { _offlineMsgCallbackUrl = value; }
    }

    private ulong _uuidTTL = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"uuidTTL", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong uuidTTL
    {
      get { return _uuidTTL; }
      set { _uuidTTL = value; }
    }

    private string _context = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"context", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string context
    {
      get { return _context; }
      set { _context = value; }
    }

    private string _messageFilter = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"messageFilter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string messageFilter
    {
      get { return _messageFilter; }
      set { _messageFilter = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MIMCPacket")]
  public partial class MIMCPacket : global::ProtoBuf.IExtensible
  {
    public MIMCPacket() {}
    

    private string _packetId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"packetId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string packetId
    {
      get { return _packetId; }
      set { _packetId = value; }
    }

    private string _package = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"package", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string package
    {
      get { return _package; }
      set { _package = value; }
    }

    private long _sequence = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sequence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long sequence
    {
      get { return _sequence; }
      set { _sequence = value; }
    }

    private mimc.MIMC_MSG_TYPE _type = mimc.MIMC_MSG_TYPE.P2P_MESSAGE;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(mimc.MIMC_MSG_TYPE.P2P_MESSAGE)]
    public mimc.MIMC_MSG_TYPE type
    {
      get { return _type; }
      set { _type = value; }
    }

    private byte[] _payload = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"payload", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] payload
    {
      get { return _payload; }
      set { _payload = value; }
    }

    private long _timestamp = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MIMCPacketList")]
  public partial class MIMCPacketList : global::ProtoBuf.IExtensible
  {
    public MIMCPacketList() {}
    

    private long _uuid = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }

    private string _resource = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resource
    {
      get { return _resource; }
      set { _resource = value; }
    }

    private long _maxSequence = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"maxSequence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long maxSequence
    {
      get { return _maxSequence; }
      set { _maxSequence = value; }
    }
    private readonly global::System.Collections.Generic.List<mimc.MIMCPacket> _packets = new global::System.Collections.Generic.List<mimc.MIMCPacket>();
    [global::ProtoBuf.ProtoMember(4, Name=@"packets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<mimc.MIMCPacket> packets
    {
      get { return _packets; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MIMCPacketAck")]
  public partial class MIMCPacketAck : global::ProtoBuf.IExtensible
  {
    public MIMCPacketAck() {}
    

    private string _packetId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"packetId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string packetId
    {
      get { return _packetId; }
      set { _packetId = value; }
    }

    private long _uuid = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }

    private string _resource = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resource
    {
      get { return _resource; }
      set { _resource = value; }
    }

    private long _sequence = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sequence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long sequence
    {
      get { return _sequence; }
      set { _sequence = value; }
    }

    private long _timestamp = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }

    private string _package = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"package", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string package
    {
      get { return _package; }
      set { _package = value; }
    }

    private string _errorMsg = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"errorMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string errorMsg
    {
      get { return _errorMsg; }
      set { _errorMsg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MIMCP2PMessage")]
  public partial class MIMCP2PMessage : global::ProtoBuf.IExtensible
  {
    public MIMCP2PMessage() {}
    

    private mimc.MIMCUser _from = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"from", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public mimc.MIMCUser from
    {
      get { return _from; }
      set { _from = value; }
    }

    private mimc.MIMCUser _to = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"to", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public mimc.MIMCUser to
    {
      get { return _to; }
      set { _to = value; }
    }

    private byte[] _payload = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"payload", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] payload
    {
      get { return _payload; }
      set { _payload = value; }
    }

    private bool _isStore = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isStore", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isStore
    {
      get { return _isStore; }
      set { _isStore = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MIMCP2TMessage")]
  public partial class MIMCP2TMessage : global::ProtoBuf.IExtensible
  {
    public MIMCP2TMessage() {}
    

    private mimc.MIMCUser _from = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"from", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public mimc.MIMCUser from
    {
      get { return _from; }
      set { _from = value; }
    }

    private mimc.MIMCGroup _to = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"to", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public mimc.MIMCGroup to
    {
      get { return _to; }
      set { _to = value; }
    }

    private byte[] _payload = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"payload", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] payload
    {
      get { return _payload; }
      set { _payload = value; }
    }

    private bool _isStore = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isStore", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isStore
    {
      get { return _isStore; }
      set { _isStore = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MIMCSequenceAck")]
  public partial class MIMCSequenceAck : global::ProtoBuf.IExtensible
  {
    public MIMCSequenceAck() {}
    

    private long _uuid = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }

    private string _resource = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resource
    {
      get { return _resource; }
      set { _resource = value; }
    }

    private long _sequence = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sequence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long sequence
    {
      get { return _sequence; }
      set { _sequence = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MIMCPull")]
  public partial class MIMCPull : global::ProtoBuf.IExtensible
  {
    public MIMCPull() {}
    

    private long _uuid = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }

    private string _resource = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resource
    {
      get { return _resource; }
      set { _resource = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MIMCUser")]
  public partial class MIMCUser : global::ProtoBuf.IExtensible
  {
    public MIMCUser() {}
    

    private long _appId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"appId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long appId
    {
      get { return _appId; }
      set { _appId = value; }
    }

    private string _appAccount = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"appAccount", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string appAccount
    {
      get { return _appAccount; }
      set { _appAccount = value; }
    }

    private long _uuid = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }

    private string _resource = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resource
    {
      get { return _resource; }
      set { _resource = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MIMCGroup")]
  public partial class MIMCGroup : global::ProtoBuf.IExtensible
  {
    public MIMCGroup() {}
    

    private long _appId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"appId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long appId
    {
      get { return _appId; }
      set { _appId = value; }
    }

    private long _topicId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"topicId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long topicId
    {
      get { return _topicId; }
      set { _topicId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UCGroup")]
  public partial class UCGroup : global::ProtoBuf.IExtensible
  {
    public UCGroup() {}
    

    private long _appId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"appId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long appId
    {
      get { return _appId; }
      set { _appId = value; }
    }

    private long _topicId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"topicId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long topicId
    {
      get { return _topicId; }
      set { _topicId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UCPacket")]
  public partial class UCPacket : global::ProtoBuf.IExtensible
  {
    public UCPacket() {}
    
    private mimc.MIMCUser _user;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public mimc.MIMCUser user
    {
      get { return _user; }
      set { _user = value; }
    }
    private mimc.UC_MSG_TYPE _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public mimc.UC_MSG_TYPE type
    {
      get { return _type; }
      set { _type = value; }
    }
    private byte[] _payload;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"payload", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] payload
    {
      get { return _payload; }
      set { _payload = value; }
    }
    private string _packetId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"packetId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string packetId
    {
      get { return _packetId; }
      set { _packetId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UCExchange")]
  public partial class UCExchange : global::ProtoBuf.IExtensible
  {
    public UCExchange() {}
    

    private mimc.FeInfo _feInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"feInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public mimc.FeInfo feInfo
    {
      get { return _feInfo; }
      set { _feInfo = value; }
    }
    private mimc.UCPacket _packet;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"packet", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public mimc.UCPacket packet
    {
      get { return _packet; }
      set { _packet = value; }
    }
    private string _package;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"package", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string package
    {
      get { return _package; }
      set { _package = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UCJoin")]
  public partial class UCJoin : global::ProtoBuf.IExtensible
  {
    public UCJoin() {}
    
    private mimc.UCGroup _group;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public mimc.UCGroup group
    {
      get { return _group; }
      set { _group = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UCJoinResp")]
  public partial class UCJoinResp : global::ProtoBuf.IExtensible
  {
    public UCJoinResp() {}
    
    private mimc.UCGroup _group;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public mimc.UCGroup group
    {
      get { return _group; }
      set { _group = value; }
    }
    private int _code;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int code
    {
      get { return _code; }
      set { _code = value; }
    }

    private string _message = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UCQuit")]
  public partial class UCQuit : global::ProtoBuf.IExtensible
  {
    public UCQuit() {}
    
    private mimc.UCGroup _group;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public mimc.UCGroup group
    {
      get { return _group; }
      set { _group = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UCQuitResp")]
  public partial class UCQuitResp : global::ProtoBuf.IExtensible
  {
    public UCQuitResp() {}
    
    private mimc.UCGroup _group;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public mimc.UCGroup group
    {
      get { return _group; }
      set { _group = value; }
    }
    private int _code;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int code
    {
      get { return _code; }
      set { _code = value; }
    }

    private string _message = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UCPing")]
  public partial class UCPing : global::ProtoBuf.IExtensible
  {
    public UCPing() {}
    
    private readonly global::System.Collections.Generic.List<mimc.UCGroup> _group = new global::System.Collections.Generic.List<mimc.UCGroup>();
    [global::ProtoBuf.ProtoMember(1, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<mimc.UCGroup> group
    {
      get { return _group; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UCMessage")]
  public partial class UCMessage : global::ProtoBuf.IExtensible
  {
    public UCMessage() {}
    
    private mimc.UCGroup _group;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public mimc.UCGroup group
    {
      get { return _group; }
      set { _group = value; }
    }
    private byte[] _payload;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"payload", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] payload
    {
      get { return _payload; }
      set { _payload = value; }
    }

    private long _sequence = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sequence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long sequence
    {
      get { return _sequence; }
      set { _sequence = value; }
    }

    private bool _isStore = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isStore", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isStore
    {
      get { return _isStore; }
      set { _isStore = value; }
    }

    private mimc.MIMCUser _user = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"user", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public mimc.MIMCUser user
    {
      get { return _user; }
      set { _user = value; }
    }

    private long _timestamp = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UCMessageList")]
  public partial class UCMessageList : global::ProtoBuf.IExtensible
  {
    public UCMessageList() {}
    
    private mimc.UCGroup _group;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public mimc.UCGroup group
    {
      get { return _group; }
      set { _group = value; }
    }
    private readonly global::System.Collections.Generic.List<mimc.UCMessage> _message = new global::System.Collections.Generic.List<mimc.UCMessage>();
    [global::ProtoBuf.ProtoMember(2, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<mimc.UCMessage> message
    {
      get { return _message; }
    }
  

    private long _maxSequence = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"maxSequence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long maxSequence
    {
      get { return _maxSequence; }
      set { _maxSequence = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UCSequenceAck")]
  public partial class UCSequenceAck : global::ProtoBuf.IExtensible
  {
    public UCSequenceAck() {}
    
    private mimc.UCGroup _group;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public mimc.UCGroup group
    {
      get { return _group; }
      set { _group = value; }
    }
    private long _sequence;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sequence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long sequence
    {
      get { return _sequence; }
      set { _sequence = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UCDismiss")]
  public partial class UCDismiss : global::ProtoBuf.IExtensible
  {
    public UCDismiss() {}
    
    private mimc.UCGroup _group;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"group", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public mimc.UCGroup group
    {
      get { return _group; }
      set { _group = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FeInfo")]
  public partial class FeInfo : global::ProtoBuf.IExtensible
  {
    public FeInfo() {}
    

    private string _fe_src_ip = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"fe_src_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fe_src_ip
    {
      get { return _fe_src_ip; }
      set { _fe_src_ip = value; }
    }

    private int _fe_src_port = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"fe_src_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fe_src_port
    {
      get { return _fe_src_port; }
      set { _fe_src_port = value; }
    }

    private int _fe_thread_id = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"fe_thread_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fe_thread_id
    {
      get { return _fe_thread_id; }
      set { _fe_thread_id = value; }
    }

    private ulong _fe_ucid = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"fe_ucid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong fe_ucid
    {
      get { return _fe_ucid; }
      set { _fe_ucid = value; }
    }

    private ulong _fe_sid = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"fe_sid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong fe_sid
    {
      get { return _fe_sid; }
      set { _fe_sid = value; }
    }

    private ulong _fe_seqno = default(ulong);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"fe_seqno", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong fe_seqno
    {
      get { return _fe_seqno; }
      set { _fe_seqno = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ErrorCode")]
    public enum ErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OK", Value=0)]
      OK = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INTERNAL_ERROR", Value=1)]
      INTERNAL_ERROR = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MIMC_MSG_TYPE")]
    public enum MIMC_MSG_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"P2P_MESSAGE", Value=1)]
      P2P_MESSAGE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"P2T_MESSAGE", Value=2)]
      P2T_MESSAGE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEQUENCE_ACK", Value=3)]
      SEQUENCE_ACK = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PACKET_ACK", Value=4)]
      PACKET_ACK = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PULL", Value=5)]
      PULL = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMPOUND", Value=6)]
      COMPOUND = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RTS_SIGNAL", Value=7)]
      RTS_SIGNAL = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UC_PACKET", Value=8)]
      UC_PACKET = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"UC_MSG_TYPE")]
    public enum UC_MSG_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PING", Value=1)]
      PING = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PONG", Value=2)]
      PONG = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JOIN", Value=3)]
      JOIN = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JOIN_RESP", Value=4)]
      JOIN_RESP = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUIT", Value=5)]
      QUIT = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUIT_RESP", Value=6)]
      QUIT_RESP = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEQ_ACK", Value=7)]
      SEQ_ACK = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MESSAGE", Value=8)]
      MESSAGE = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MESSAGE_LIST", Value=9)]
      MESSAGE_LIST = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DISMISS", Value=10)]
      DISMISS = 10
    }
  
}