//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: control_message.proto
/*

* ==============================================================================
*
* Filename: $safeitemname$
* Description: 
*
* Created: $time$
* Compiler: Visual Studio 2017
*
* Author: zhangming8
* Company: Xiaomi.com
*
* ==============================================================================
*/
namespace sdk.protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushServiceConfigMsg")]
  public partial class PushServiceConfigMsg : global::ProtoBuf.IExtensible
  {
    public PushServiceConfigMsg() {}
    
    private bool _fetchBucket = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"fetchBucket", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool fetchBucket
    {
      get { return _fetchBucket; }
      set { _fetchBucket = value; }
    }
    private bool _useBucketV2 = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"useBucketV2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool useBucketV2
    {
      get { return _useBucketV2; }
      set { _useBucketV2 = value; }
    }
    private int _clientVersion = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"clientVersion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int clientVersion
    {
      get { return _clientVersion; }
      set { _clientVersion = value; }
    }
    private int _cloudVersion = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"cloudVersion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cloudVersion
    {
      get { return _cloudVersion; }
      set { _cloudVersion = value; }
    }
    private int _dots = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"dots", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dots
    {
      get { return _dots; }
      set { _dots = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}