//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ims_push_service.proto
// Note: requires additional types generated from: control_message.proto
/*

* ==============================================================================
*
* Filename: $safeitemname$
* Description: 
*
* Created: $time$
* Compiler: Visual Studio 2017
*
* Author: zhangming8
* Company: Xiaomi.com
*
* ==============================================================================
*/
namespace sdk.protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientHeader")]
  public partial class ClientHeader : global::ProtoBuf.IExtensible
  {
    public ClientHeader() {}
    
    private int _chid = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"chid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chid
    {
      get { return _chid; }
      set { _chid = value; }
    }
    private long _uuid = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private string _server = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"server", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string server
    {
      get { return _server; }
      set { _server = value; }
    }
    private string _resource = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resource
    {
      get { return _resource; }
      set { _resource = value; }
    }
    private string _cmd = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private string _subcmd = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"subcmd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string subcmd
    {
      get { return _subcmd; }
      set { _subcmd = value; }
    }
    private string _id = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
        private sdk.protobuf.ClientHeader.MSG_DIR_FLAG _dir_flag = sdk.protobuf.ClientHeader.MSG_DIR_FLAG.CS_ONEWAY;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"dir_flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(sdk.protobuf.ClientHeader.MSG_DIR_FLAG.CS_ONEWAY)]
        public sdk.protobuf.ClientHeader.MSG_DIR_FLAG dir_flag
    {
      get { return _dir_flag; }
      set { _dir_flag = value; }
    }
    private int _cipher = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"cipher", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cipher
    {
      get { return _cipher; }
      set { _cipher = value; }
    }
    private int _err_code = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"err_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int err_code
    {
      get { return _err_code; }
      set { _err_code = value; }
    }
    private string _err_str = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"err_str", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string err_str
    {
      get { return _err_str; }
      set { _err_str = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MSG_DIR_FLAG")]
    public enum MSG_DIR_FLAG
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_ONEWAY", Value=1)]
      CS_ONEWAY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_REQ", Value=2)]
      CS_REQ = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_RESP", Value=3)]
      CS_RESP = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SC_ONEWAY", Value=4)]
      SC_ONEWAY = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SC_REQ", Value=5)]
      SC_REQ = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SC_RESP", Value=6)]
      SC_RESP = 6
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XMMsgConn")]
  public partial class XMMsgConn : global::ProtoBuf.IExtensible
  {
    public XMMsgConn() {}
    
    private uint _version = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint version
    {
      get { return _version; }
      set { _version = value; }
    }
    private string _model = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"model", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string model
    {
      get { return _model; }
      set { _model = value; }
    }
    private string _os = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"os", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string os
    {
      get { return _os; }
      set { _os = value; }
    }
    private string _udid = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"udid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string udid
    {
      get { return _udid; }
      set { _udid = value; }
    }
    private int _sdk = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sdk", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sdk
    {
      get { return _sdk; }
      set { _sdk = value; }
    }
    private string _connpt = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"connpt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string connpt
    {
      get { return _connpt; }
      set { _connpt = value; }
    }
    private string _host = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"host", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string host
    {
      get { return _host; }
      set { _host = value; }
    }
    private string _locale = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"locale", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string locale
    {
      get { return _locale; }
      set { _locale = value; }
    }
    private protocol.PushServiceConfigMsg _psc = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"psc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protocol.PushServiceConfigMsg psc
    {
      get { return _psc; }
      set { _psc = value; }
    }
    private int _andver = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"andver", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int andver
    {
      get { return _andver; }
      set { _andver = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XMMsgConnResp")]
  public partial class XMMsgConnResp : global::ProtoBuf.IExtensible
  {
    public XMMsgConnResp() {}
    
    private string _challenge = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"challenge", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string challenge
    {
      get { return _challenge; }
      set { _challenge = value; }
    }
    private string _host = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"host", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string host
    {
      get { return _host; }
      set { _host = value; }
    }
    private protocol.PushServiceConfigMsg _psc = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"psc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protocol.PushServiceConfigMsg psc
    {
      get { return _psc; }
      set { _psc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XMMsgBind")]
  public partial class XMMsgBind : global::ProtoBuf.IExtensible
  {
    public XMMsgBind() {}
    
    private string _token = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private string _kick = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"kick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string kick
    {
      get { return _kick; }
      set { _kick = value; }
    }
    private string _method = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"method", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string method
    {
      get { return _method; }
      set { _method = value; }
    }
    private string _client_attrs = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"client_attrs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string client_attrs
    {
      get { return _client_attrs; }
      set { _client_attrs = value; }
    }
    private string _cloud_attrs = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"cloud_attrs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cloud_attrs
    {
      get { return _cloud_attrs; }
      set { _cloud_attrs = value; }
    }
    private string _sig = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"sig", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sig
    {
      get { return _sig; }
      set { _sig = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XMMsgBindResp")]
  public partial class XMMsgBindResp : global::ProtoBuf.IExtensible
  {
    public XMMsgBindResp() {}
    
    private bool _result = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool result
    {
      get { return _result; }
      set { _result = value; }
    }
    private string _error_type = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"error_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string error_type
    {
      get { return _error_type; }
      set { _error_type = value; }
    }
    private string _error_reason = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"error_reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string error_reason
    {
      get { return _error_reason; }
      set { _error_reason = value; }
    }
    private string _error_desc = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"error_desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string error_desc
    {
      get { return _error_desc; }
      set { _error_desc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XMMsgPing")]
  public partial class XMMsgPing : global::ProtoBuf.IExtensible
  {
    public XMMsgPing() {}
    
    private byte[] _stats = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"stats", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] stats
    {
      get { return _stats; }
      set { _stats = value; }
    }
    private protocol.PushServiceConfigMsg _psc = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"psc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protocol.PushServiceConfigMsg psc
    {
      get { return _psc; }
      set { _psc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XMMsgNotify")]
  public partial class XMMsgNotify : global::ProtoBuf.IExtensible
  {
    public XMMsgNotify() {}
    
    private int _err_code = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"err_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int err_code
    {
      get { return _err_code; }
      set { _err_code = value; }
    }
    private string _err_str = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"err_str", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string err_str
    {
      get { return _err_str; }
      set { _err_str = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}