//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: mimc.proto
/*

* ==============================================================================
*
* Filename: $safeitemname$
* Description: 
*
* Created: $time$
* Compiler: Visual Studio 2017
*
* Author: zhangming8
* Company: Xiaomi.com
*
* ==============================================================================
*/
namespace mimc
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PullMessageRequest")]
  public partial class PullMessageRequest : global::ProtoBuf.IExtensible
  {
    public PullMessageRequest() {}
    
    private ulong _uuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }
    private string _resource;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string resource
    {
      get { return _resource; }
      set { _resource = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TopicMessage")]
  public partial class TopicMessage : global::ProtoBuf.IExtensible
  {
    public TopicMessage() {}
    
    private ulong _topicId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"topicId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong topicId
    {
      get { return _topicId; }
      set { _topicId = value; }
    }
    private MIMCPacket _packet;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"packet", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MIMCPacket packet
    {
      get { return _packet; }
      set { _packet = value; }
    }

    private long _uuid = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }

    private string _resource = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resource
    {
      get { return _resource; }
      set { _resource = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QueryAppinfoRequest")]
  public partial class QueryAppinfoRequest : global::ProtoBuf.IExtensible
  {
    public QueryAppinfoRequest() {}
    
    private ulong _appId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"appId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong appId
    {
      get { return _appId; }
      set { _appId = value; }
    }

    private string _context = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"context", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string context
    {
      get { return _context; }
      set { _context = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Appinfo")]
  public partial class Appinfo : global::ProtoBuf.IExtensible
  {
    public Appinfo() {}
    
    private ulong _appId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"appId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong appId
    {
      get { return _appId; }
      set { _appId = value; }
    }

    private string _msgCallbackUrl = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"msgCallbackUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string msgCallbackUrl
    {
      get { return _msgCallbackUrl; }
      set { _msgCallbackUrl = value; }
    }

    private string _offlineMsgCallbackUrl = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"offlineMsgCallbackUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string offlineMsgCallbackUrl
    {
      get { return _offlineMsgCallbackUrl; }
      set { _offlineMsgCallbackUrl = value; }
    }

    private ulong _uuidTTL = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"uuidTTL", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong uuidTTL
    {
      get { return _uuidTTL; }
      set { _uuidTTL = value; }
    }

    private string _context = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"context", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string context
    {
      get { return _context; }
      set { _context = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MIMCPacket")]
  public partial class MIMCPacket : global::ProtoBuf.IExtensible
  {
    public MIMCPacket() {}
    

    private string _packetId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"packetId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string packetId
    {
      get { return _packetId; }
      set { _packetId = value; }
    }

    private string _package = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"package", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string package
    {
      get { return _package; }
      set { _package = value; }
    }

    private long _sequence = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sequence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long sequence
    {
      get { return _sequence; }
      set { _sequence = value; }
    }

    private MIMC_MSG_TYPE _type = MIMC_MSG_TYPE.P2P_MESSAGE;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MIMC_MSG_TYPE.P2P_MESSAGE)]
    public MIMC_MSG_TYPE type
    {
      get { return _type; }
      set { _type = value; }
    }

    private byte[] _payload = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"payload", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] payload
    {
      get { return _payload; }
      set { _payload = value; }
    }

    private long _timestamp = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MIMCPacketList")]
  public partial class MIMCPacketList : global::ProtoBuf.IExtensible
  {
    public MIMCPacketList() {}
    

    private long _uuid = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }

    private string _resource = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resource
    {
      get { return _resource; }
      set { _resource = value; }
    }

    private long _maxSequence = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"maxSequence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long maxSequence
    {
      get { return _maxSequence; }
      set { _maxSequence = value; }
    }
    private readonly global::System.Collections.Generic.List<MIMCPacket> _packets = new global::System.Collections.Generic.List<MIMCPacket>();
    [global::ProtoBuf.ProtoMember(4, Name=@"packets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MIMCPacket> packets
    {
      get { return _packets; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MIMCPacketAck")]
  public partial class MIMCPacketAck : global::ProtoBuf.IExtensible
  {
    public MIMCPacketAck() {}
    

    private string _packetId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"packetId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string packetId
    {
      get { return _packetId; }
      set { _packetId = value; }
    }

    private long _uuid = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }

    private string _resource = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resource
    {
      get { return _resource; }
      set { _resource = value; }
    }

    private long _sequence = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sequence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long sequence
    {
      get { return _sequence; }
      set { _sequence = value; }
    }

    private long _timestamp = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }

    private string _package = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"package", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string package
    {
      get { return _package; }
      set { _package = value; }
    }

    private string _errorMsg = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"errorMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string errorMsg
    {
      get { return _errorMsg; }
      set { _errorMsg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MIMCP2PMessage")]
  public partial class MIMCP2PMessage : global::ProtoBuf.IExtensible
  {
    public MIMCP2PMessage() {}
    

    private MIMCUser _from = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"from", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MIMCUser from
    {
      get { return _from; }
      set { _from = value; }
    }

    private MIMCUser _to = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"to", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MIMCUser to
    {
      get { return _to; }
      set { _to = value; }
    }

    private byte[] _payload = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"payload", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] payload
    {
      get { return _payload; }
      set { _payload = value; }
    }

    private bool _isStore = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isStore", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isStore
    {
      get { return _isStore; }
      set { _isStore = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MIMCP2TMessage")]
  public partial class MIMCP2TMessage : global::ProtoBuf.IExtensible
  {
    public MIMCP2TMessage() {}
    

    private MIMCUser _from = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"from", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MIMCUser from
    {
      get { return _from; }
      set { _from = value; }
    }

    private MIMCGroup _to = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"to", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MIMCGroup to
    {
      get { return _to; }
      set { _to = value; }
    }

    private byte[] _payload = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"payload", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] payload
    {
      get { return _payload; }
      set { _payload = value; }
    }

    private bool _isStore = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isStore", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isStore
    {
      get { return _isStore; }
      set { _isStore = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MIMCSequenceAck")]
  public partial class MIMCSequenceAck : global::ProtoBuf.IExtensible
  {
    public MIMCSequenceAck() {}
    

    private long _uuid = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }

    private string _resource = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resource
    {
      get { return _resource; }
      set { _resource = value; }
    }

    private long _sequence = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sequence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long sequence
    {
      get { return _sequence; }
      set { _sequence = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MIMCPull")]
  public partial class MIMCPull : global::ProtoBuf.IExtensible
  {
    public MIMCPull() {}
    

    private long _uuid = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }

    private string _resource = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resource
    {
      get { return _resource; }
      set { _resource = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MIMCUser")]
  public partial class MIMCUser : global::ProtoBuf.IExtensible
  {
    public MIMCUser() {}
    

    private long _appId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"appId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long appId
    {
      get { return _appId; }
      set { _appId = value; }
    }

    private string _appAccount = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"appAccount", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string appAccount
    {
      get { return _appAccount; }
      set { _appAccount = value; }
    }

    private long _uuid = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"uuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long uuid
    {
      get { return _uuid; }
      set { _uuid = value; }
    }

    private string _resource = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resource
    {
      get { return _resource; }
      set { _resource = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MIMCGroup")]
  public partial class MIMCGroup : global::ProtoBuf.IExtensible
  {
    public MIMCGroup() {}
    

    private long _appId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"appId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long appId
    {
      get { return _appId; }
      set { _appId = value; }
    }

    private long _topicId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"topicId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long topicId
    {
      get { return _topicId; }
      set { _topicId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MIMC_MSG_TYPE")]
    public enum MIMC_MSG_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"P2P_MESSAGE", Value=1)]
      P2P_MESSAGE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"P2T_MESSAGE", Value=2)]
      P2T_MESSAGE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEQUENCE_ACK", Value=3)]
      SEQUENCE_ACK = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PACKET_ACK", Value=4)]
      PACKET_ACK = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PULL", Value=5)]
      PULL = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMPOUND", Value=6)]
      COMPOUND = 6
    }
  
}